# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_czTkDaFz9d9kEfSHYVEJ1qL73MuRGK
"""

joint_pos_and_disease = 0.0099
joint_pos_and_no_disease = 0.0495

P_positive = joint_pos_and_disease + joint_pos_and_no_disease

print("🔹 Addition Step")
print(f"Total P(Positive): {P_positive:.5f}")

P_disease_given_positive = joint_pos_and_disease / P_positive

print("\n🔹 Final Result Using Bayes' Theorem")
print(f"P(Disease | Positive): {P_disease_given_positive:.5f}")