# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121tPhyREMa6r9Mp_ysavjFCqbqDjJ80e
"""

P_disease = 0.01
P_no_disease = 1 - P_disease

P_pos_given_disease = 0.99
P_pos_given_no_disease = 0.05

joint_pos_and_disease = P_pos_given_disease * P_disease
joint_pos_and_no_disease = P_pos_given_no_disease * P_no_disease

print("🔹 Multiplication Step")
print(f"P(Positive ∩ Disease): {joint_pos_and_disease:.5f}")
print(f"P(Positive ∩ No Disease): {joint_pos_and_no_disease:.5f}")